// Look of the expression input and its tooltips (completion list, docs,
// signature help). Everything uses the app's CSS variables; the extra
// syntax colors (`--yx-*`) are defined in ExprInput.svelte with light and
// dark values. Tooltips live in document.body but get the editor's theme
// classes, so these rules apply there too.

import { EditorView } from '@codemirror/view';

const ui = "system-ui, -apple-system, 'Segoe UI', sans-serif";
const shadow = '0 6px 24px rgba(0, 0, 0, 0.18), 0 1px 3px rgba(0, 0, 0, 0.12)';

export const exprTheme = EditorView.theme({
  '&': { backgroundColor: 'transparent', color: 'var(--fg)', fontSize: 'inherit', flex: '1', minWidth: '0' },
  '&.cm-focused': { outline: 'none' },
  '.cm-scroller': { fontFamily: 'inherit', lineHeight: '18px', scrollbarWidth: 'none' },
  '.cm-scroller::-webkit-scrollbar': { display: 'none' },
  '.cm-content': { padding: '3px 0', caretColor: 'var(--fg)' },
  '.cm-line': { padding: '0 6px' },
  '.cm-cursor, .cm-dropCursor': { borderLeftColor: 'var(--fg)' },
  '&.cm-focused > .cm-scroller > .cm-selectionLayer .cm-selectionBackground, .cm-selectionBackground, ::selection': { backgroundColor: 'var(--sel) !important' },
  '.cm-placeholder': { color: 'var(--muted)', fontStyle: 'normal' },

  // ---------------------------------------------------------- syntax
  '.yx-num, .yx-color, .yx-bool': { color: 'var(--syn-number)' },
  '.yx-unit': { color: 'var(--syn-number)', opacity: '0.7' },
  '.yx-str': { color: 'var(--syn-string)' },
  '.yx-ref': { color: 'var(--yx-ref)', fontWeight: '600' },
  '.yx-ref-field': { color: 'var(--yx-ref)' },
  '.yx-param': { color: 'var(--yx-param)' },
  '.yx-local': { color: 'var(--yx-param)', fontStyle: 'italic' },
  '.yx-builtin': { color: 'var(--syn-key)' },
  '.yx-prop': { color: 'var(--fg)' },
  '.yx-fn': { color: 'var(--syn-keyword)', fontWeight: '600' },
  '.yx-keyword': { color: 'var(--syn-key)', fontWeight: '600' },
  '.yx-op, .yx-punct': { color: 'var(--muted)' },
  '.yx-unknown': { textDecoration: 'underline wavy var(--warn)', textUnderlineOffset: '3px', textDecorationSkipInk: 'none' },
  '.yx-error': { color: 'var(--err)', textDecoration: 'underline wavy var(--err)', textUnderlineOffset: '3px' },
  '.yx-hole': { backgroundColor: 'var(--yx-hole)', borderRadius: '2px' },
  '.yx-brace': { color: 'var(--accent)', fontWeight: '700', backgroundColor: 'var(--yx-hole)' },
  '.yx-escape': { color: 'var(--muted)' },
  '.yx-swatch': {
    display: 'inline-block',
    width: '9px',
    height: '9px',
    margin: '0 2px 0 3px',
    verticalAlign: '-1px',
    borderRadius: '2px',
    background: 'linear-gradient(var(--c), var(--c)), repeating-conic-gradient(var(--check-a) 0 25%, var(--check-b) 0 50%) 0 0 / 6px 6px',
    boxShadow: 'inset 0 0 0 1px rgba(127, 127, 127, 0.45)',
  },

  // ---------------------------------------------------------- tooltips
  '.cm-tooltip': {
    backgroundColor: 'var(--bg)',
    color: 'var(--fg)',
    border: '1px solid var(--line)',
    borderRadius: '6px',
    boxShadow: shadow,
    fontFamily: ui,
    fontSize: '12px',
    zIndex: '1000',
  },
  '.cm-tooltip.cm-tooltip-autocomplete': { padding: '3px' },
  '.cm-tooltip.cm-tooltip-autocomplete > ul': { fontFamily: ui, maxHeight: '260px', minWidth: '240px', maxWidth: '420px' },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > li': {
    display: 'flex',
    alignItems: 'center',
    gap: '7px',
    padding: '3px 8px 3px 5px',
    borderRadius: '4px',
    lineHeight: '17px',
  },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > li[aria-selected]': { backgroundColor: 'var(--sel)', color: 'var(--fg)' },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > li.yx-dim': { opacity: '0.55' },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > li.yx-dim[aria-selected]': { opacity: '0.85' },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > completion-section': {
    display: 'block',
    padding: '6px 8px 2px',
    fontSize: '10px',
    fontWeight: '600',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: 'var(--muted)',
    borderBottom: 'none',
    opacity: '1',
  },
  '.cm-completionLabel': { fontFamily: 'var(--mono)', fontSize: '12px' },
  '.cm-completionMatchedText': { textDecoration: 'none', color: 'var(--accent)', fontWeight: '600' },
  '.cm-completionDetail': {
    marginLeft: 'auto',
    paddingLeft: '14px',
    fontStyle: 'normal',
    color: 'var(--muted)',
    fontFamily: 'var(--mono)',
    fontSize: '11px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '200px',
  },
  '.yx-badge': {
    flex: 'none',
    width: '16px',
    height: '16px',
    lineHeight: '16px',
    textAlign: 'center',
    borderRadius: '4px',
    fontSize: '10px',
    fontWeight: '700',
    fontFamily: 'var(--mono)',
    color: 'var(--bg)',
    backgroundColor: 'var(--muted)',
  },
  '.yx-badge-param': { backgroundColor: 'var(--yx-param)' },
  '.yx-badge-local': { backgroundColor: 'var(--yx-param)' },
  '.yx-badge-layer': { backgroundColor: 'var(--yx-ref)' },
  '.yx-badge-builtin': { backgroundColor: 'var(--syn-key)' },
  '.yx-badge-fn': { backgroundColor: 'var(--syn-keyword)', fontStyle: 'italic', fontFamily: 'Georgia, serif', fontSize: '12px' },
  '.yx-badge-keyword': { backgroundColor: 'var(--syn-key)' },
  '.yx-badge-key': { backgroundColor: 'var(--yx-param)' },
  '.yx-badge-field': { backgroundColor: 'transparent', color: 'var(--muted)', boxShadow: 'inset 0 0 0 1px var(--line)' },
  '.cm-tooltip.cm-completionInfo': { padding: '8px 10px', width: '260px', maxWidth: '260px', lineHeight: '1.45' },
  '.yx-info-head': { fontFamily: 'var(--mono)', fontSize: '12px', fontWeight: '600', marginBottom: '4px', wordBreak: 'break-word' },
  '.yx-info-body': { color: 'var(--fg)' },
  '.yx-info-extra': { marginTop: '6px', color: 'var(--muted)', fontFamily: 'var(--mono)', fontSize: '11px', whiteSpace: 'pre-wrap' },
  '.yx-info-warn': {
    marginTop: '6px',
    padding: '3px 6px',
    borderRadius: '4px',
    color: 'var(--warn-text)',
    backgroundColor: 'color-mix(in srgb, var(--warn) 14%, transparent)',
  },
  '.yx-sig': { fontFamily: 'var(--mono)' },
  '.yx-sig-arg': { color: 'var(--fg)' },
  '.yx-sig-active': { color: 'var(--accent)', fontWeight: '700', textDecoration: 'underline', textUnderlineOffset: '3px' },
  '.yx-sighelp': { fontSize: '12px', padding: '5px 9px', maxWidth: '380px' },
  '.yx-sighelp-doc': { marginTop: '2px', color: 'var(--muted)', fontSize: '11px' },
});
